//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChustaSoft.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChustaSoft.Common.Resources.ExceptionResources", typeof(ExceptionResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data property is null, for adding elements, SetData method must be called before..
        /// </summary>
        internal static string ArgumentException_ActionResponseBuilder_DataNull {
            get {
                return ResourceManager.GetString("ArgumentException_ActionResponseBuilder_DataNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String could not be empty or nulll..
        /// </summary>
        internal static string ArgumentException_StringHelper_WrongString {
            get {
                return ResourceManager.GetString("ArgumentException_StringHelper_WrongString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported Enum type or string case..
        /// </summary>
        internal static string ArgumentException_UnsupportedEnumCast {
            get {
                return ResourceManager.GetString("ArgumentException_UnsupportedEnumCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element of type {0} could not be found..
        /// </summary>
        internal static string ElementNotFoundException_Type_ErrorMessage {
            get {
                return ResourceManager.GetString("ElementNotFoundException_Type_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no element of type {0} matching with selected property name {1}..
        /// </summary>
        internal static string ElementNotFoundException_TypeAndError_ErrorMessage {
            get {
                return ResourceManager.GetString("ElementNotFoundException_TypeAndError_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element: {0} not found in {1} type..
        /// </summary>
        internal static string EnumNotFoundException_ErrorMessage {
            get {
                return ResourceManager.GetString("EnumNotFoundException_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Index out of range..
        /// </summary>
        internal static string InvalidOperationException_PageIndexError {
            get {
                return ResourceManager.GetString("InvalidOperationException_PageIndexError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PaginatedList do not allow to add elements..
        /// </summary>
        internal static string InvalidOperationException_PaginatedListAdd {
            get {
                return ResourceManager.GetString("InvalidOperationException_PaginatedListAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model of type {0} cannot be mapped to model of type {1}.
        /// </summary>
        internal static string ModelMappingException_ErrorMessage {
            get {
                return ResourceManager.GetString("ModelMappingException_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} algorithm not supported for the requested operation..
        /// </summary>
        internal static string UnsupportedAlgorithmException_ErrorMessage {
            get {
                return ResourceManager.GetString("UnsupportedAlgorithmException_ErrorMessage", resourceCulture);
            }
        }
    }
}
