<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<IsPackable>false</IsPackable>
	</PropertyGroup>

	<ItemGroup>
		<None Remove="Resources\test-json-file.json" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="Resources\test-json-file.json" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
		<PackageReference Include="MSTest.TestAdapter" Version="4.0.2" />
		<PackageReference Include="MSTest.TestFramework" Version="4.0.2" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\ChustaSoft.Common\ChustaSoft.Common.csproj" />
	</ItemGroup>

</Project>
